name = "quicksend"
main = "src/index.js"
compatibility_date = "2024-12-27"

# [vars]
# R2_ACCESS_KEY_ID = ""
# R2_SECRET_ACCESS_KEY = ""
# R2_ENDPOINT = "https://YOUR-R2-URL.r2.cloudflarestorage.com"
# R2_BUCKET_NAME = "YOUR-BUCKET-NAME"
# SUPABASE_URL = "https://SUPABASE-URL.supabase.co"
# SUPABASE_ANON_KEY = "eyJ..."

[[rules]]
type = "Text"
globs = ["**/*.html"]
